### ISSUE TITLE
running virtualhost test1 on external server

### ISSUE THREAD

**Issue by s33k3rs** [Worteks/ldapcon2019-llng-workshop#1]
I have successfully installed and runing step by step tutorials in this workshop, but when I copy test1 as test3 on virtual host external server, access to test3 virtual host is successfully redirected to auth on the main server, but after login it can't redirect again to virtual host test3, an error appears:

```
The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

This problem can sometimes be caused by disabling or refusing to accept cookies.

```
is there anything that needs to be changed when running the code test1 on external server?

**Comment by coudot** [comment]
Did you install LL::NG Handler on an externel server? It requires to share configuration and sessions in this case.

**Comment by s33k3rs** [comment]
Yes i did

This is my configuration

**1. Main Server (ip address 10.50.1.11)**
/etc/hosts
```
127.0.0.1	localhost auth.example.com manager.example.com test1.example.com test2.example.com fd.example.com dokuwiki.example.com
127.0.1.1	llng-workshop.worteks.com	llng-workshop
10.50.1.12	test3.example.com

# The following lines are desirable for IPv6 capable hosts
#::1     localhost ip6-localhost ip6-loopback
#ff02::1 ip6-allnodes
#ff02::2 ip6-allrouters
```

**2. External server / test3.example.com (ip address 10.50.1.12)**
/etc/hosts
```
127.0.0.1	localhost test3.example.com
127.0.1.1	test3.example.com	test3
10.50.1.11 auth.example.com manager.example.com test1.example.com test2.example.com
10.50.1.12 test3.example.com

# The following lines are desirable for IPv6 capable hosts
#::1     localhost ip6-localhost ip6-loopback
#ff02::1 ip6-allnodes
#ff02::2 ip6-allrouters
```

add LemonLDAP::NG repository to /etc/apt/sources.list
install apache2 and LemonLDAP::NG by
```
apt install apache2 libapache2-mod-perl2 libapache2-mod-fcgid
apt install lemonldap-ng
```

Create VirtualHost test3-apache2.conf
```
#====================================================================
# Apache configuration for LemonLDAP::NG sample applications
#====================================================================

# Uncomment this if no previous NameVirtualHost declaration
#NameVirtualHost "*:80"
PerlModule Lemonldap::NG::Handler::ApacheMP2::Menu

# Sample application
<VirtualHost "*:80">
    ServerName test3.example.com
#    ServerAlias test3.example.com

    # SSO protection
    PerlHeaderParserHandler Lemonldap::NG::Handler::ApacheMP2

    # DocumentRoot
    DocumentRoot /var/lib/lemonldap-ng/test/
    <Directory /var/lib/lemonldap-ng/test/>
        <IfVersion >= 2.3>
            Require all granted
        </IfVersion>
        <IfVersion < 2.3>
            Order Deny,Allow
            Allow from all
        </IfVersion>
        Options +ExecCGI
    </Directory>

    # Perl script (application test is written in Perl)
    <Files *.pl>
        SetHandler perl-script
        PerlResponseHandler ModPerl::Registry

        # Display Menu
        PerlOutputFilterHandler Lemonldap::NG::Handler::ApacheMP2::Menu->run

    </Files>

    # Directory index
    <IfModule mod_dir.c>
        DirectoryIndex index.pl index.html
    </IfModule>

    # Uncomment this if site if you use SSL only
    #Header set Strict-Transport-Security "max-age=15768000"
</VirtualHost>

```

activate Virtual Host by
a2ensite test3-apache2.conf 
a2enmod fcgid perl alias rewrite headers

**3. manager.example.com** 

Add Application Menu on manager.example.com - General Parameters > Portal > Menu > Categories and applications > Sample applications

Add Accest rules and Exported headers on  manager.example.com > Virtual Hosts > test3.example.com

I only enable test3-apache2.conf virtualhost configuration on the external server, is there anything i missed?

**Comment by coudot** [comment]
Hello @s33k3rs 

it can not work like this. Your other server must be able to read configuration and sessions on the main portal server. This tutorial is not build to attach an external server. It requires to share config and sessions for example with REST (see https://lemonldap-ng.org/documentation/latest/restsessionbackend.html and https://lemonldap-ng.org/documentation/latest/restconfbackend.html)

But maybe you should do a clean installation of LL::NG on a dedicated server, and not use the tutorial image for this.

**Comment by s33k3rs** [comment]
thank you for the instructions, 

Okay I'll try to reinstall from scratch and use REST method

**Comment by s33k3rs** [comment]
Finally after reinstalling from scratch and trying several times, I successfully connected 3 virtual servers between
Zimbra Directory Service (LDAP) as authentication database, LemonLDAP :: NG, and running test-apache2 on external server

Thank you for your guidance
